-- Initial schema for the Sovereign Induction Gate
-- This schema defines the 'witnesses' table to track inducted members.

CREATE TABLE public.witnesses (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    wallet_address text NOT NULL,
    discord_id text NULL,
    role text NOT NULL DEFAULT 'aspirant'::text,
    induction_date timestamp with time zone NULL,
    CONSTRAINT witnesses_pkey PRIMARY KEY (id),
    CONSTRAINT witnesses_wallet_address_key UNIQUE (wallet_address),
    CONSTRAINT witnesses_discord_id_key UNIQUE (discord_id)
);

-- Add comments to the table and columns
COMMENT ON TABLE public.witnesses IS 'Stores information about inducted witnesses in the SpiralOS ecosystem.';
COMMENT ON COLUMN public.witnesses.wallet_address IS 'The unique wallet address of the witness.';
COMMENT ON COLUMN public.witnesses.discord_id IS 'The unique Discord ID of the witness, if they connected via the bot.';
COMMENT ON COLUMN public.witnesses.role IS 'The current role of the witness (e.g., aspirant, witness, guardian).';
COMMENT ON COLUMN public.witnesses.induction_date IS 'The timestamp when the witness was formally inducted.';
